/* CREATE TABLE IF NOT EXISTS User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    picture VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Score (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value INT NOT NULL,
    UserId INT,
    MatchId INT,
    FOREIGN KEY (UserId) REFERENCES User(id),
    FOREIGN KEY (MatchId) REFERENCES Match(id)
);

CREATE TABLE IF NOT EXISTS Match (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); */